startWeapons   = ["rhsusf_weap_MP7A2","rhs_weap_ak74m","rhs_weap_M136","rhs_weap_M590_5RD","rhsusf_weap_glock17g4"];
startMagazines = ["rhsusf_mag_17Rnd_9x19_FMJ","rhsusf_5Rnd_00Buck","rhsusf_5Rnd_Slug"];
startItems     = ["ItemGPS","FirstAidKit","ToolKit","acc_flashlight_pistol","acc_flashlight","rhs_acc_2dpZenit"];
startBackpacks = [];


rand_weapons = [
					"rhs_weap_ak74m",
					"rhs_weap_asval",

					"rhs_weap_asval_npz",
					"rhs_weap_vss",
					
					"rhs_weap_vss_npz",
					"rhs_weap_ak74m_zenitco01",
					"rhs_weap_ak74m_zenitco01_afg",
					"rhs_weap_ak74m_zenitco01_npz",
					"rhs_weap_ak74m_zenitco01_npz_afg",
					"rhs_weap_ak74m_zenitco01_b33",
					"rhs_weap_ak74m_zenitco01_b33_afg",
					"rhs_weap_ak74mr",
					"rhs_weap_ak74mr_afg",
					"rhs_weap_ak74mr_gp25",
					"rhs_weap_ak105",
					"rhs_weap_ak105_zenitco01",
					"rhs_weap_ak105_zenitco01_afg",
					"rhs_weap_ak105_zenitco01_npz",
					"rhs_weap_ak105_zenitco01_npz_afg",
					"rhs_weap_ak105_npz",
					"rhs_weap_ak105_zenitco01_b33",
					"rhs_weap_ak105_zenitco01_b33_afg",
					"rhs_weap_ak74m_camo",
					"rhs_weap_ak74m_npz",
					"rhs_weap_ak74m_desert_npz",
					"rhs_weap_ak74m_camo_npz",
					"rhs_weap_akm",
					"rhs_weap_akm_gp25",
					"rhs_weap_akms",
					"rhs_weap_akms_gp25",
					"rhs_weap_ak103",
					"rhs_weap_ak104",
					"rhs_weap_ak104_npz",
					"rhs_weap_ak104_zenitco01",
					"rhs_weap_ak104_zenitco01_afg",
					"rhs_weap_ak104_zenitco01_npz",
					"rhs_weap_ak104_zenitco01_npz_afg",
					"rhs_weap_ak104_zenitco01_b33",
					"rhs_weap_ak104_zenitco01_b33_afg",
					"rhs_weap_ak103_npz",
					"rhs_weap_ak103_zenitco01",
					"rhs_weap_ak103_zenitco01_afg",
					"rhs_weap_ak103_zenitco01_npz",
					"rhs_weap_ak103_zenitco01_npz_afg",
					"rhs_weap_ak103_zenitco01_b33",
					"rhs_weap_ak103_zenitco01_b33_afg",
					"rhs_weap_ak103_1",
					"rhs_weap_ak103_1_npz",
					"rhs_weap_ak103_2",
					"rhs_weap_ak103_2_npz",
					"rhs_weap_ak103_gp25",
					"rhs_weap_ak103_gp25_npz",
					"rhs_weap_ak74m_2mag",
					"rhs_weap_ak74m_2mag_npz",
					"rhs_weap_ak74m_2mag_camo_npz",
					"rhs_weap_ak74m_2mag_camo",
					"rhs_weap_ak74m_desert",
					"rhs_weap_ak74m_plummag",
					"rhs_weap_ak74m_plummag_npz",
					"rhs_weap_ak74m_gp25",
					"rhs_weap_ak74m_gp25_npz",
					"rhs_weap_ak74m_fullplum",
					"rhs_weap_ak74m_fullplum_npz",
					"rhs_weap_ak74m_fullplum_gp25",
					"rhs_weap_ak74m_fullplum_gp25_npz",
					"rhs_weap_ak74",
					"rhs_weap_ak74_gp25",
					"rhs_weap_ak74n",
					"rhs_weap_ak74n_gp25",
					"rhs_weap_ak74n_npz",
					"rhs_weap_ak74n_gp25_npz",
					"rhs_weap_ak74_2",
					"rhs_weap_ak74_3",
					"rhs_weap_aks74",
					"rhs_weap_aks74_2",
					"rhs_weap_aks74_gp25",
					"rhs_weap_aks74n",
					"rhs_weap_aks74n_npz",
					"rhs_weap_aks74n_gp25",
					"rhs_weap_aks74n_gp25_npz",
					"rhs_weap_aks74u",
					"rhs_weap_aks74un",
					"rhs_weap_svdp",
					"rhs_weap_svdp_npz",
					"rhs_weap_svdp_wd",
					"rhs_weap_svdp_wd_npz",
					"rhs_weap_svds",
					"rhs_weap_svds_npz",
					"rhs_weap_t5000",
					"rhs_weap_pp2000",
					"rhs_weap_pp2000_folded",
					"rhs_weap_pya",
					"rhs_weap_rsp30_white",
					"rhs_weap_rsp30_red",
					"rhs_weap_rsp30_green",
					"rhs_weap_tr8",
					"rhs_weap_makarov_pm",
					"rhs_weap_pkp",
					"rhs_weap_pkm",
					"rhs_weap_rshg2",

					"rhs_weap_igla",
					"rhs_weap_kar98k",
					"rhs_weap_m38",
					"rhs_weap_m38_rail",
					"rhs_weap_m70ab2",
					"rhs_weap_m70b1",
					"rhs_weap_m92",
					"rhs_weap_m76",
					"rhs_weap_m21a",
					"rhs_weap_m21a_pr",
					"rhs_weap_m21s",
					"rhs_weap_m21s_pr",
					"rhs_weap_savz61",
					"rhs_weap_M320",
					"rhs_weap_XM2010",
					"rhs_weap_XM2010_d",
					"rhs_weap_XM2010_wd",
					"rhs_weap_XM2010_sa",
					"rhs_weap_m24sws",
					"rhs_weap_m24sws_blk",
					"rhs_weap_m24sws_ghillie",
					"rhs_weap_m40a5",
					"rhs_weap_m40a5_d",
					"rhs_weap_m40a5_wd",
					"rhs_weap_m4",
					"rhs_weap_m4_pmag",
					"rhs_weap_m4_mstock",
					"rhs_weap_m4_carryhandle",
					"rhs_weap_m4_carryhandle_pmag",
					"rhs_weap_m4_carryhandle_mstock",
					"rhs_weap_m4_m320",
					"rhs_weap_m4_m203",
					"rhs_weap_m4_m203S",
					"rhs_weap_m4a1",
					"rhs_weap_m4a1_d",
					"rhs_weap_m4a1_mstock",
					"rhs_weap_m4a1_d_mstock",
					"rhs_weap_m4a1_pmag",
					"rhs_weap_m4a1_carryhandle",
					"rhs_weap_m4a1_carryhandle_mstock",
					"rhs_weap_m4a1_carryhandle_pmag",
					"rhs_weap_m4a1_m203",
					"rhs_weap_m4a1_m203s",
					"rhs_weap_m4a1_m203s_d",
					"rhs_weap_m4a1_carryhandle_m203",
					"rhs_weap_m4a1_carryhandle_m203S",
					"rhs_weap_m4a1_m320",
					"rhs_weap_mk18",
					"rhs_weap_mk18_bk",
					"rhs_weap_mk18_wd",
					"rhs_weap_mk18_d",
					"rhs_weap_mk18_KAC",
					"rhs_weap_mk18_KAC_bk",
					"rhs_weap_mk18_KAC_wd",
					"rhs_weap_mk18_KAC_d",
					"rhs_weap_mk18_m320",
					"rhs_weap_m16a4",
					"rhs_weap_m16a4_pmag",
					"rhs_weap_m16a4_carryhandle",
					"rhs_weap_m16a4_carryhandle_pmag",
					"rhs_weap_m16a4_carryhandle_M203",
					"rhs_weap_hk416d10",
					"rhs_weap_hk416d145",
					"rhs_weap_hk416d10_LMT",
					"rhs_weap_hk416d10_m320",
					"rhs_weap_hk416d145_m320",
					"rhs_weap_hk416d10_LMT_d",
					"rhs_weap_hk416d10_LMT_wd",
					"rhs_weap_m27iar",
					"rhs_weap_m249",
					"rhs_weap_m249_pip_S",
					"rhs_weap_m249_pip_S_para",
					"rhs_weap_m249_pip_S_vfg",
					"rhs_weap_m249_pip",
					"rhs_weap_m249_pip_L",
					"rhs_weap_m249_pip_L_para",
					"rhs_weap_m249_pip_L_vfg",
					"rhs_weap_m240B",
					"rhs_weap_m240G",
					"rhs_weap_m240B_CAP",
					"rhs_weap_m14ebrri",
					"rhs_weap_sr25",
					"rhs_weap_sr25_ec",
					"rhs_weap_sr25_wd",
					"rhs_weap_sr25_ec_wd",
					"rhs_weap_sr25_d",
					"rhs_weap_sr25_ec_d",
					"rhs_weap_M107",
					"rhs_weap_M107_d",
					"rhs_weap_M107_w",
					"rhs_weap_M590_5RD",
					"rhs_weap_M590_8RD",
					"rhs_weap_m32",
					"rhsusf_weap_MP7A2",
					"rhsusf_weap_MP7A2_winter",
					"rhsusf_weap_MP7A2_desert",
					"rhsusf_weap_MP7A2_aor1",


					"rhs_weap_fim92",
					"rhsusf_weap_m1911a1",
					"rhsusf_weap_glock17g4",
					"rhsusf_weap_m9",
					"rhsgref_weap_svds",
					"rhs_weap_g36c",
					"rhs_weap_g36kv",
					"rhs_weap_g36kv_ag36",
					"rhs_weap_m84",
					"rhs_weap_minimi_para_railed"
				];
				
rand_rhsLauncher = [
						// Javelin
						"rhs_weap_fgm148",

						// normal launcher
						"rhs_weap_rpg26","rhs_weap_rshg2","rhs_weap_rpg7","rhs_weap_smaw","rhs_weap_smaw_green","rhs_weap_M136","rhs_weap_M136_hedp","rhs_weap_M136_hp","rhs_weap_m72a7",

						// AA launchers
						"rhs_weap_igla","rhs_weap_fim92"
					];

rand_rhsJavelinLauncher =	[
								"rhs_weap_fgm148"
							];

//rand_items_two append ("(_x call smm_fnc_macrosIsGood) and (_x call smm_fnc_macrosIsItem) and (_x call smm_is_not_thermal) && (count (configName _x) > 3) && (toLower ((configName _x) select [0,3])) == 'rhs' && (isNumber (_x >> 'ItemInfo' >> 'type' )) && (getNumber (_x >> 'ItemInfo' >> 'type') in [101, 201, 301, 302])" configClasses (configFile >> "CfgWeapons") apply {configName _x});
rand_items_one append ["rhs_bipod","rhs_acc_harris_swivel","rhs_acc_tgpa","rhs_acc_pbs1","rhs_acc_tgpv","rhs_acc_tgpv2","rhs_acc_dtk4short","rhs_acc_dtk4long","rhs_acc_dtk4screws","rhs_acc_pbs4","rhs_acc_6p9_suppressor","rhs_acc_dtk3","rhs_acc_dtk","rhs_acc_dtkakm","rhs_acc_dtk1983","rhs_acc_dtk1","rhs_acc_dtk1l","rhs_acc_dtk1p","rhs_acc_dtk2","rhs_acc_uuk","rhs_acc_ak5","rhs_acc_pgs64","rhs_acc_pgs64_74u","rhs_acc_pgs64_74un","rhs_acc_1p29","rhs_acc_1p78","rhs_acc_pkas","rhs_acc_1p63","rhs_acc_ekp1","rhs_acc_ekp8_02","rhs_acc_ekp8_18","rhs_acc_1p87","rhs_acc_pso1m2","rhs_acc_pso1m21","rhs_acc_nita","rhs_acc_pgo7v","rhs_acc_pgo7v2","rhs_acc_pgo7v3","rhs_acc_1pn93_1","rhs_acc_1pn93_2","rhs_acc_dh520x56","rhs_acc_2dpZenit","rhs_acc_2dpZenit_ris","rhs_acc_perst1ik","rhs_acc_perst1ik_ris","rhs_acc_perst3","rhs_acc_perst3_top","rhs_acc_perst3_2dp_h","rhs_acc_perst3_2dp_light_h","rhs_acc_rakursPM","rhs_acc_grip_rk2","rhs_acc_grip_rk6","rhs_acc_grip_ffg2","rhs_item_flightrecorder","rhsgref_sdn6_suppressor","rhsgref_acc_zendl","rhsusf_acc_harris_bipod","rhsusf_acc_harris_swivel","rhsusf_acc_grip1","rhsusf_acc_grip2","rhsusf_acc_grip2_tan","rhsusf_acc_grip2_wd","rhsusf_acc_grip3","rhsusf_acc_grip3_tan","rhsusf_acc_grip4","rhs_acc_at4_handler","rhsusf_acc_anpeq15A","rhsusf_acc_anpeq15","rhsusf_acc_anpeq15_bk","rhsusf_acc_anpeq15_light","rhsusf_acc_anpeq15_bk_light","rhsusf_acc_anpeq15_wmx","rhsusf_acc_anpeq15_wmx_light","rhsusf_acc_anpeq15_top","rhsusf_acc_anpeq15_bk_top","rhsusf_acc_anpeq15side","rhsusf_acc_anpeq15side_bk","rhsusf_acc_M952V","rhsusf_acc_wmx","rhsusf_acc_wmx_bk","rhsusf_acc_M2010S","rhsusf_acc_M2010S_d","rhsusf_acc_M2010S_sa","rhsusf_acc_M2010S_wd","rhsusf_acc_SR25S","rhsusf_acc_rotex5_grey","rhsusf_acc_rotex5_tan","rhsusf_acc_nt4_black","rhsusf_acc_nt4_tan","rhsusf_acc_omega9k","rhsusf_acc_rotex_mp7","rhsusf_acc_rotex_mp7_aor1","rhsusf_acc_rotex_mp7_winter","rhsusf_acc_rotex_mp7_desert","rhsusf_acc_SF3P556","rhsusf_acc_SFMB556","rhsusf_acc_ARDEC_M240","rhsusf_acc_compm4","rhsusf_acc_T1_high","rhsusf_acc_T1_low","rhsusf_acc_T1_low_fwd","rhsusf_acc_eotech_552","rhsusf_acc_eotech_552_d","rhsusf_acc_eotech_552_wd","rhsusf_acc_anpvs27","rhsusf_acc_LEUPOLDMK4","rhsusf_acc_ELCAN","rhsusf_acc_ELCAN_ard","rhsusf_acc_SpecterDR","rhsusf_acc_SpecterDR_D","rhsusf_acc_SpecterDR_OD","rhsusf_acc_SpecterDR_CX","rhsusf_acc_SpecterDR_A","rhsusf_acc_ACOG","rhsusf_acc_ACOG_wd","rhsusf_acc_ACOG_d","rhsusf_acc_ACOG2","rhsusf_acc_ACOG3","rhsusf_acc_ACOG_USMC","rhsusf_acc_ACOG2_USMC","rhsusf_acc_ACOG3_USMC","rhsusf_acc_ACOG_RMR","rhsusf_acc_ACOG_anpvs27","rhsusf_acc_LEUPOLDMK4_2","rhsusf_acc_LEUPOLDMK4_2_d","rhsusf_acc_premier","rhsusf_acc_premier_low","rhsusf_acc_premier_anpvs27","rhsusf_acc_M8541","rhsusf_acc_M8541_low","rhsusf_acc_M8541_low_d","rhsusf_acc_M8541_low_wd","rhsusf_acc_EOTECH","rhsusf_acc_M2A1","rhsusf_acc_eotech_xps3","rhsusf_acc_ACOG_MDO","rhsusf_acc_g33_xps3","rhsusf_acc_g33_xps3_tan","rhsusf_acc_g33_T1","rhs_weap_optic_smaw","rhs_optic_maaws"];

//rand_items_one append (("(_x call smm_fnc_macrosIsGood) and (_x call smm_fnc_macrosIsItem) and (_x call smm_is_not_thermal) && (count (configName _x) > 3) && (toLower ((configName _x) select [0,3])) == 'rhs' && !(isText (_x >> 'ItemInfo' >> 'uniformClass'))" configClasses (configFile >> "CfgWeapons") apply {configName _x}) - rand_items_two);
rand_items_two append ["rhssaf_helmet_m59_85_nocamo","rhssaf_helmet_m59_85_oakleaf","rhssaf_helmet_m97_olive_nocamo","rhssaf_helmet_m97_olive_nocamo_black_ess","rhssaf_helmet_m97_olive_nocamo_black_ess_bare","rhssaf_helmet_m97_black_nocamo","rhssaf_helmet_m97_black_nocamo_black_ess","rhssaf_helmet_m97_black_nocamo_black_ess_bare","rhssaf_helmet_m97_woodland","rhssaf_helmet_m97_digital","rhssaf_helmet_m97_md2camo","rhssaf_helmet_m97_oakleaf","rhssaf_helmet_m97_nostrap_blue","rhssaf_helmet_m97_nostrap_blue_tan_ess","rhssaf_helmet_m97_nostrap_blue_tan_ess_bare","rhssaf_helmet_m97_woodland_black_ess","rhssaf_helmet_m97_digital_black_ess","rhssaf_helmet_m97_md2camo_black_ess","rhssaf_helmet_m97_oakleaf_black_ess","rhssaf_helmet_m97_woodland_black_ess_bare","rhssaf_helmet_m97_digital_black_ess_bare","rhssaf_helmet_m97_md2camo_black_ess_bare","rhssaf_helmet_m97_oakleaf_black_ess_bare","rhssaf_beret_green","rhssaf_beret_red","rhssaf_beret_para","rhssaf_beret_black","rhssaf_beret_blue_un","rhs_booniehat2_marpatd","rhssaf_booniehat_digital","rhssaf_booniehat_md2camo","rhssaf_booniehat_woodland","rhssaf_bandana_digital","rhssaf_bandana_digital_desert","rhssaf_bandana_oakleaf","rhssaf_bandana_smb","rhssaf_bandana_md2camo","rhssaf_vest_md98_woodland","rhssaf_vest_md98_md2camo","rhssaf_vest_md98_digital","rhssaf_vest_md98_rifleman","rhssaf_vest_otv_md2camo","rhssaf_vest_md99_md2camo_rifleman","rhssaf_vest_md99_md2camo_rifleman_radio","rhssaf_vest_md99_digital_rifleman","rhssaf_vest_md99_digital_rifleman_radio","rhssaf_vest_md99_woodland_rifleman","rhssaf_vest_md99_woodland_rifleman_radio","rhssaf_vest_md99_md2camo","rhssaf_vest_md99_md2camo_radio","rhssaf_vest_md99_digital","rhssaf_vest_md99_digital_radio","rhssaf_vest_md99_woodland","rhssaf_vest_md99_woodland_radio","rhssaf_vest_md12_digital","rhssaf_vest_md12_m70_rifleman","rhssaf_vest_md12_digital_desert","rhs_bipod","rhs_acc_harris_swivel","rhs_muzzleFlash_dtk","rhs_muzzleFlash_dtk1","rhs_muzzleFlash_dtk2","rhs_muzzleFlash_dtk3","rhs_muzzleFlash_ak5","rhs_muzzleFlash_uuk","rhs_muzzleflash_pgs64","rhs_muzzleflash_dtkakm","rhs_acc_tgpa","rhs_acc_pbs1","rhs_acc_tgpv","rhs_acc_tgpv2","rhs_acc_dtk4short","rhs_acc_dtk4long","rhs_acc_dtk4screws","rhs_acc_pbs4","rhs_acc_6p9_suppressor","rhs_acc_dtk3","rhs_acc_dtk","rhs_acc_dtkakm","rhs_acc_dtk1983","rhs_acc_dtk1","rhs_acc_dtk1l","rhs_acc_dtk1p","rhs_acc_dtk2","rhs_acc_uuk","rhs_acc_ak5","rhs_acc_pgs64","rhs_acc_pgs64_74u","rhs_acc_pgs64_74un","rhs_acc_1p29","rhs_acc_1p78","rhs_acc_pkas","rhs_acc_1p63","rhs_acc_ekp1","rhs_acc_ekp8_02","rhs_acc_ekp8_18","rhs_acc_1p87","rhs_acc_pso1m2","rhs_acc_pso1m21","rhs_acc_nita","rhs_acc_pgo7v","rhs_acc_pgo7v2","rhs_acc_pgo7v3","rhs_acc_1pn93_1","rhs_acc_1pn93_2","rhs_acc_dh520x56","rhs_acc_2dpZenit","rhs_acc_2dpZenit_ris","rhs_acc_perst1ik","rhs_acc_perst1ik_ris","rhs_acc_perst3","rhs_acc_perst3_top","rhs_acc_perst3_2dp_h","rhs_acc_perst3_2dp_light_h","rhs_acc_rakursPM","rhs_acc_grip_rk2","rhs_acc_grip_rk6","rhs_acc_grip_ffg2","rhs_item_flightrecorder","rhsgref_sdn6_suppressor","rhsgref_acc_zendl","rhsusf_acc_harris_bipod","rhsusf_acc_harris_swivel","rhsusf_acc_grip1","rhsusf_acc_grip2","rhsusf_acc_grip2_tan","rhsusf_acc_grip2_wd","rhsusf_acc_grip3","rhsusf_acc_grip3_tan","rhsusf_acc_grip4","rhs_acc_at4_handler","rhsusf_acc_anpeq15A","rhsusf_acc_anpeq15","rhsusf_acc_anpeq15_bk","rhsusf_acc_anpeq15_light","rhsusf_acc_anpeq15_bk_light","rhsusf_acc_anpeq15_wmx","rhsusf_acc_anpeq15_wmx_light","rhsusf_acc_anpeq15_top","rhsusf_acc_anpeq15_bk_top","rhsusf_acc_anpeq15side","rhsusf_acc_anpeq15side_bk","rhsusf_acc_M952V","rhsusf_acc_wmx","rhsusf_acc_wmx_bk","rhsusf_acc_M2010S","rhsusf_acc_M2010S_d","rhsusf_acc_M2010S_sa","rhsusf_acc_M2010S_wd","rhsusf_acc_SR25S","rhsusf_acc_rotex5_grey","rhsusf_acc_rotex5_tan","rhsusf_acc_nt4_black","rhsusf_acc_nt4_tan","rhsusf_acc_omega9k","rhsusf_acc_rotex_mp7","rhsusf_acc_rotex_mp7_aor1","rhsusf_acc_rotex_mp7_winter","rhsusf_acc_rotex_mp7_desert","rhsusf_acc_muzzleFlash_SF3P556","rhsusf_acc_muzzleFlash_SFMB556","rhsusf_acc_muzzleFlash_ardec_m240","rhsusf_acc_SF3P556","rhsusf_acc_SFMB556","rhsusf_acc_ARDEC_M240","rhsusf_acc_compm4","rhsusf_acc_T1_high","rhsusf_acc_T1_low","rhsusf_acc_T1_low_fwd","rhsusf_acc_eotech_552","rhsusf_acc_eotech_552_d","rhsusf_acc_eotech_552_wd","rhsusf_acc_anpvs27","rhsusf_acc_LEUPOLDMK4","rhsusf_acc_ELCAN","rhsusf_acc_ELCAN_ard","rhsusf_acc_SpecterDR","rhsusf_acc_SpecterDR_D","rhsusf_acc_SpecterDR_OD","rhsusf_acc_SpecterDR_CX","rhsusf_acc_SpecterDR_A","rhsusf_acc_ACOG","rhsusf_acc_ACOG_wd","rhsusf_acc_ACOG_d","rhsusf_acc_ACOG2","rhsusf_acc_ACOG3","rhsusf_acc_ACOG_USMC","rhsusf_acc_ACOG2_USMC","rhsusf_acc_ACOG3_USMC","rhsusf_acc_ACOG_RMR","rhsusf_acc_ACOG_anpvs27","rhsusf_acc_LEUPOLDMK4_2","rhsusf_acc_LEUPOLDMK4_2_d","rhsusf_acc_premier","rhsusf_acc_premier_low","rhsusf_acc_premier_anpvs27","rhsusf_acc_M8541","rhsusf_acc_M8541_low","rhsusf_acc_M8541_low_d","rhsusf_acc_M8541_low_wd","rhsusf_acc_EOTECH","rhsusf_acc_M2A1","rhsusf_acc_eotech_xps3","rhsusf_acc_ACOG_MDO","rhsusf_acc_g33_xps3","rhsusf_acc_g33_xps3_tan","rhsusf_acc_g33_T1","rhs_weap_optic_smaw","rhs_optic_maaws","rhs_fieldcap","rhs_fieldcap_vsr","rhs_fieldcap_digi","rhs_fieldcap_digi2","rhs_fieldcap_ml","rhs_fieldcap_khk","rhs_fieldcap_helm","rhs_fieldcap_helm_digi","rhs_fieldcap_helm_ml","rhs_beanie","rhs_beanie_green","rhs_6b26","rhs_6b26_bala","rhs_6b26_ess","rhs_6b26_ess_bala","rhs_6b26_green","rhs_6b26_bala_green","rhs_6b26_ess_green","rhs_6b26_ess_bala_green","rhs_6b27m","rhs_6b27m_digi","rhs_6b27m_ml","rhs_6b27m_ess_bala","rhs_6b27m_digi_ess_bala","rhs_6b27m_ML_ess_bala","rhs_6b27m_bala","rhs_6b27m_digi_bala","rhs_6b27m_ml_bala","rhs_6b27m_ess","rhs_6b27m_digi_ess","rhs_6b27m_ml_ess","rhs_6b27m_green","rhs_6b27m_green_ess","rhs_6b27m_green_bala","rhs_6b27m_green_ess_bala","rhs_6b28","rhs_6b28_flora","rhs_6b28_ess","rhs_6b28_flora_ess","rhs_6b28_bala","rhs_6b28_flora_bala","rhs_6b28_ess_bala","rhs_6b28_flora_ess_bala","rhs_6b28_green","rhs_6b28_green_ess","rhs_6b28_green_bala","rhs_6b28_green_ess_bala","rhs_Booniehat_digi","rhs_Booniehat_flora","rhs_ssh68","rhs_zsh7a","rhs_zsh7a_alt","rhs_zsh7a_mike","rhs_zsh7a_mike_green","rhs_zsh7a_mike_alt","rhs_zsh7a_mike_green_alt","rhs_gssh18","rhs_tsh4","rhs_tsh4_ess","rhs_tsh4_bala","rhs_tsh4_ess_bala","rhs_6b47","rhs_6b47_bala","rhs_6b47_ess","rhs_6b47_ess_bala","rhs_6b7_1m","rhs_6b7_1m_ess","rhs_6b7_1m_ess_bala","rhs_6b7_1m_bala1","rhs_6b7_1m_bala1_emr","rhs_6b7_1m_emr_ess","rhs_6b7_1m_emr_ess_bala","rhs_6b7_1m_bala1_flora","rhs_6b7_1m_bala1_olive","rhs_6b7_1m_bala2","rhs_6b7_1m_bala2_emr","rhs_6b7_1m_bala2_flora","rhs_6b7_1m_bala2_olive","rhs_6b7_1m_emr","rhs_6b7_1m_flora","rhs_6b7_1m_flora_ns3","rhs_6b7_1m_olive","rhs_altyn","rhs_altyn_bala","rhs_altyn_visordown","rhs_altyn_novisor","rhs_altyn_novisor_bala","rhs_altyn_novisor_ess","rhs_altyn_novisor_ess_bala","rhs_beret_vdv1","rhs_beret_vdv2","rhs_beret_mp1","rhs_beret_milp","rhs_beret_vdv3","rhs_beret_mp2","rhs_6b23","rhs_6b23_crew","rhs_6b23_engineer","rhs_6b23_medic","rhs_6b23_rifleman","rhs_6b23_crewofficer","rhs_6b23_sniper","rhs_6b23_6sh92","rhs_6b23_6sh92_vog","rhs_6b23_6sh92_vog_headset","rhs_6b23_6sh92_headset","rhs_6b23_6sh92_headset_mapcase","rhs_6b23_6sh92_radio","rhs_6sh46","rhs_vest_commander","rhs_vest_pistol_holster","rhs_6b23_digi","rhs_6b23_digi_crew","rhs_6b23_digi_engineer","rhs_6b23_digi_medic","rhs_6b23_digi_rifleman","rhs_6b23_digi_crewofficer","rhs_6b23_digi_sniper","rhs_6b23_digi_6sh92","rhs_6b23_digi_6sh92_vog","rhs_6b23_digi_6sh92_vog_headset","rhs_6b23_digi_6sh92_headset","rhs_6b23_digi_6sh92_headset_mapcase","rhs_6b23_digi_6sh92_radio","rhs_6b23_digi_6sh92_Spetsnaz","rhs_6b23_digi_6sh92_Vog_Radio_Spetsnaz","rhs_6b23_digi_6sh92_headset_spetsnaz","rhs_6b23_digi_6sh92_spetsnaz2","rhs_6b23_digi_6sh92_Vog_Spetsnaz","rhs_6b23_ML","rhs_6b23_ML_crew","rhs_6b23_ML_engineer","rhs_6b23_ML_medic","rhs_6b23_ML_rifleman","rhs_6b23_ML_crewofficer","rhs_6b23_ML_sniper","rhs_6b23_ML_6sh92","rhs_6b23_ML_6sh92_vog","rhs_6b23_ML_6sh92_vog_headset","rhs_6b23_ML_6sh92_headset","rhs_6b23_ML_6sh92_headset_mapcase","rhs_6b23_ML_6sh92_radio","rhs_vydra_3m","rhs_6b23_vydra_3m","rhs_6b23_digi_vydra_3m","rhs_6b23_ML_vydra_3m","rhs_6b23_6sh116","rhs_6b23_6sh116_flora","rhs_6b23_6sh116_od","rhs_6b23_6sh116_vog","rhs_6b23_6sh116_vog_flora","rhs_6b23_6sh116_vog_od","rhs_6b13","rhs_6b13_crewofficer","rhs_6b13_6sh92","rhs_6b13_6sh92_vog","rhs_6b13_6sh92_headset_mapcase","rhs_6b13_6sh92_radio","rhs_6b13_EMR","rhs_6b13_EMR_6sh92","rhs_6b13_EMR_6sh92_vog","rhs_6b13_EMR_6sh92_headset_mapcase","rhs_6b13_EMR_6sh92_radio","rhs_6b13_Flora","rhs_6b13_Flora_crewofficer","rhs_6b13_Flora_6sh92","rhs_6b13_Flora_6sh92_vog","rhs_6b13_Flora_6sh92_headset_mapcase","rhs_6b13_Flora_6sh92_radio","rhs_6b43","rhs_6sh92","rhs_6sh92_vog","rhs_6sh92_vog_headset","rhs_6sh92_headset","rhs_6sh92_radio","rhs_6sh92_digi","rhs_6sh92_digi_vog","rhs_6sh92_digi_vog_headset","rhs_6sh92_digi_headset","rhs_6sh92_digi_radio","rhs_6sh92_vsr","rhs_6sh92_vsr_vog","rhs_6sh92_vsr_vog_headset","rhs_6sh92_vsr_headset","rhs_6sh92_vsr_radio","rhsgref_un_beret","rhsgref_Booniehat_alpen","rhsgref_bcap_specter","rhsgref_patrolcap_specter","rhsgref_fieldcap_ttsko_forest","rhsgref_fieldcap_ttsko_mountain","rhsgref_fieldcap_ttsko_urban","rhsgref_fieldcap_ttsko_digi","rhsgref_ssh68_ttsko_mountain","rhsgref_ssh68_ttsko_forest","rhsgref_ssh68_ttsko_dark","rhsgref_ssh68_ttsko_digi","rhsgref_ssh68_emr","rhsgref_ssh68_un","rhsgref_ssh68_vsr","rhsgref_M56","rhsgref_6b27m_ttsko_forest","rhsgref_6b27m_ttsko_mountain","rhsgref_6b27m_ttsko_urban","rhsgref_6b27m_ttsko_digi","rhsgref_helmet_M1_bare","rhsgref_helmet_M1_bare_alt01","rhsgref_helmet_M1_painted","rhsgref_helmet_M1_painted_alt01","rhsgref_helmet_pasgt_erdl","rhsgref_helmet_pasgt_erdl_rhino","rhsgref_helmet_pasgt_woodland","rhsgref_helmet_pasgt_woodland_rhino","rhsgref_helmet_pasgt_flecktarn","rhsgref_helmet_pasgt_un","rhsgref_helmet_pasgt_press","rhsgref_helmet_pasgt_3color_desert","rhsgref_helmet_pasgt_3color_desert_rhino","rhsgref_helmet_pasgt_altis_lizard","rhsgref_helmet_pasgt_olive","rhsgref_6b23_khaki","rhsgref_6b23_khaki_rifleman","rhsgref_6b23_khaki_sniper","rhsgref_6b23_khaki_officer","rhsgref_6b23_khaki_nco","rhsgref_6b23_khaki_medic","rhsgref_6b23_ttsko_forest","rhsgref_6b23_ttsko_forest_rifleman","rhsgref_6b23_ttsko_mountain","rhsgref_6b23_ttsko_mountain_rifleman","rhsgref_6b23_ttsko_mountain_sniper","rhsgref_6b23_ttsko_mountain_officer","rhsgref_6b23_ttsko_mountain_nco","rhsgref_6b23_ttsko_mountain_medic","rhsgref_6b23_ttsko_digi","rhsgref_6b23_ttsko_digi_rifleman","rhsgref_6b23_ttsko_digi_sniper","rhsgref_6b23_ttsko_digi_officer","rhsgref_6b23_ttsko_digi_nco","rhsgref_6b23_ttsko_digi_medic","rhs_6b5","rhs_6b5_officer","rhs_6b5_medic","rhs_6b5_sniper","rhs_6b5_khaki","rhs_6b5_officer_khaki","rhs_6b5_medic_khaki","rhs_6b5_sniper_khaki","rhs_6b5_vsr","rhs_6b5_officer_vsr","rhs_6b5_medic_vsr","rhs_6b5_sniper_vsr","rhs_6b5_ttsko","rhs_6b5_officer_ttsko","rhs_6b5_medic_ttsko","rhs_6b5_sniper_ttsko","rhsgref_otv_khaki","rhsgref_otv_digi","rhsgref_TacVest_ERDL","rhsgref_alice_webbing","rhsusf_patrolcap_ocp","rhsusf_patrolcap_ucp","rhs_Booniehat_ocp","rhs_Booniehat_ucp","rhs_Booniehat_m81","rhs_booniehat2_marpatwd","rhs_8point_marpatd","rhs_8point_marpatwd","rhsusf_ach_helmet_ocp","rhsusf_ach_helmet_ocp_norotos","rhsusf_ach_helmet_ucp","rhsusf_ach_helmet_ucp_norotos","rhsusf_ach_helmet_M81","rhsusf_ach_helmet_camo_ocp","rhsusf_ach_helmet_headset_ocp","rhsusf_ach_helmet_headset_ucp","rhsusf_ach_helmet_ESS_ocp","rhsusf_ach_helmet_ESS_ucp","rhsusf_ach_helmet_headset_ess_ocp","rhsusf_ach_helmet_headset_ess_ucp","rhsusf_ach_bare","rhsusf_ach_bare_ess","rhsusf_ach_bare_headset","rhsusf_ach_bare_headset_ess","rhsusf_ach_bare_tan","rhsusf_ach_bare_tan_ess","rhsusf_ach_bare_tan_headset","rhsusf_ach_bare_tan_headset_ess","rhsusf_ach_bare_wood","rhsusf_ach_bare_wood_ess","rhsusf_ach_bare_wood_headset","rhsusf_ach_bare_wood_headset_ess","rhsusf_ach_bare_des","rhsusf_ach_bare_des_ess","rhsusf_ach_bare_des_headset","rhsusf_ach_bare_des_headset_ess","rhsusf_ach_bare_semi","rhsusf_ach_bare_semi_ess","rhsusf_ach_bare_semi_headset","rhsusf_ach_bare_semi_headset_ess","rhsusf_opscore_fg","rhsusf_opscore_fg_pelt","rhsusf_opscore_fg_pelt_nsw","rhsusf_opscore_fg_pelt_cam","rhsusf_opscore_ut","rhsusf_opscore_ut_pelt","rhsusf_opscore_ut_pelt_cam","rhsusf_opscore_ut_pelt_nsw","rhsusf_opscore_ut_pelt_nsw_cam","rhsusf_opscore_bk","rhsusf_opscore_bk_pelt","rhsusf_opscore_mc","rhsusf_opscore_mc_pelt","rhsusf_opscore_mc_pelt_nsw","rhsusf_opscore_aor1","rhsusf_opscore_aor1_pelt","rhsusf_opscore_aor1_pelt_nsw","rhsusf_opscore_aor2","rhsusf_opscore_aor2_pelt","rhsusf_opscore_aor2_pelt_nsw","rhsusf_opscore_paint","rhsusf_opscore_paint_pelt","rhsusf_opscore_paint_pelt_nsw","rhsusf_opscore_paint_pelt_nsw_cam","rhsusf_opscore_mc_cover","rhsusf_opscore_mc_cover_pelt","rhsusf_opscore_mc_cover_pelt_nsw","rhsusf_opscore_mc_cover_pelt_cam","rhsusf_opscore_rg_cover","rhsusf_opscore_rg_cover_pelt","rhsusf_opscore_coy_cover","rhsusf_opscore_coy_cover_pelt","rhsusf_opscore_mar_ut","rhsusf_opscore_mar_ut_pelt","rhsusf_opscore_mar_fg","rhsusf_opscore_mar_fg_pelt","rhsusf_cvc_helmet","rhsusf_cvc_alt_helmet","rhsusf_cvc_green_helmet","rhsusf_cvc_green_alt_helmet","rhsusf_cvc_ess","rhsusf_cvc_green_ess","rhsusf_hgu56p","rhsusf_hgu56p_visor","rhsusf_hgu56p_mask","rhsusf_hgu56p_visor_mask","rhsusf_hgu56p_visor_mask_skull","rhsusf_hgu56p_mask_skull","rhsusf_hgu56p_visor_mask_mo","rhsusf_hgu56p_mask_mo","rhsusf_hgu56p_mask_smiley","rhsusf_hgu56p_visor_mask_smiley","rhsusf_hgu56p_black","rhsusf_hgu56p_visor_black","rhsusf_hgu56p_mask_black","rhsusf_hgu56p_visor_mask_black","rhsusf_hgu56p_visor_mask_black_skull","rhsusf_hgu56p_mask_black_skull","rhsusf_hgu56p_visor_mask_Empire_black","rhsusf_hgu56p_green","rhsusf_hgu56p_visor_green","rhsusf_hgu56p_mask_green","rhsusf_hgu56p_visor_mask_green","rhsusf_hgu56p_mask_green_mo","rhsusf_hgu56p_visor_mask_green_mo","rhsusf_hgu56p_pink","rhsusf_hgu56p_visor_pink","rhsusf_hgu56p_mask_pink","rhsusf_hgu56p_visor_mask_pink","rhsusf_hgu56p_usa","rhsusf_hgu56p_visor_usa","rhsusf_hgu56p_saf","rhsusf_hgu56p_visor_saf","rhsusf_hgu56p_mask_saf","rhsusf_hgu56p_visor_mask_saf","rhsusf_mich_helmet_marpatwd","rhsusf_mich_helmet_marpatwd_headset","rhsusf_mich_helmet_marpatd","rhsusf_mich_helmet_marpatd_headset","rhsusf_mich_helmet_marpatwd_alt","rhsusf_mich_helmet_marpatwd_alt_headset","rhsusf_mich_helmet_marpatd_alt","rhsusf_mich_helmet_marpatd_alt_headset","rhsusf_mich_helmet_marpatwd_norotos","rhsusf_mich_helmet_marpatwd_norotos_headset","rhsusf_mich_helmet_marpatd_norotos","rhsusf_mich_helmet_marpatd_norotos_headset","rhsusf_mich_helmet_marpatwd_norotos_arc","rhsusf_mich_helmet_marpatwd_norotos_arc_headset","rhsusf_mich_helmet_marpatd_norotos_arc","rhsusf_mich_helmet_marpatd_norotos_arc_headset","rhsusf_mich_bare","rhsusf_mich_bare_headset","rhsusf_mich_bare_alt","rhsusf_mich_bare_norotos","rhsusf_mich_bare_norotos_headset","rhsusf_mich_bare_norotos_alt","rhsusf_mich_bare_norotos_alt_headset","rhsusf_mich_bare_norotos_arc","rhsusf_mich_bare_norotos_arc_headset","rhsusf_mich_bare_norotos_arc_alt","rhsusf_mich_bare_norotos_arc_alt_headset","rhsusf_mich_bare_tan","rhsusf_mich_bare_tan_headset","rhsusf_mich_bare_alt_tan","rhsusf_mich_bare_norotos_tan","rhsusf_mich_bare_norotos_tan_headset","rhsusf_mich_bare_norotos_alt_tan","rhsusf_mich_bare_norotos_alt_tan_headset","rhsusf_mich_bare_norotos_arc_tan","rhsusf_mich_bare_norotos_arc_alt_tan","rhsusf_mich_bare_norotos_arc_alt_tan_headset","rhsusf_mich_bare_semi","rhsusf_mich_bare_semi_headset","rhsusf_mich_bare_alt_semi","rhsusf_mich_bare_norotos_semi","rhsusf_mich_bare_norotos_semi_headset","rhsusf_mich_bare_norotos_alt_semi","rhsusf_mich_bare_norotos_alt_semi_headset","rhsusf_mich_bare_norotos_arc_semi","rhsusf_mich_bare_norotos_arc_semi_headset","rhsusf_mich_bare_norotos_arc_alt_semi","rhsusf_mich_bare_norotos_arc_alt_semi_headset","rhsusf_lwh_helmet_marpatd","rhsusf_lwh_helmet_marpatd_ess","rhsusf_lwh_helmet_marpatd_headset","rhsusf_lwh_helmet_marpatwd","rhsusf_lwh_helmet_marpatwd_ess","rhsusf_lwh_helmet_marpatwd_blk_ess","rhsusf_lwh_helmet_marpatwd_headset","rhsusf_lwh_helmet_marpatwd_headset_blk","rhsusf_lwh_helmet_M1942","rhsusf_Bowman","rhsusf_bowman_cap","RHS_jetpilot_usaf","rhsusf_protech_helmet","rhsusf_protech_helmet_ess","rhsusf_protech_helmet_rhino","rhsusf_protech_helmet_rhino_ess","rhsusf_iotv_ocp","rhsusf_iotv_ocp_Grenadier","rhsusf_iotv_ocp_Medic","rhsusf_iotv_ocp_Repair","rhsusf_iotv_ocp_Rifleman","rhsusf_iotv_ocp_SAW","rhsusf_iotv_ocp_Squadleader","rhsusf_iotv_ocp_Teamleader","rhsusf_iotv_ucp","rhsusf_iotv_ucp_Grenadier","rhsusf_iotv_ucp_Medic","rhsusf_iotv_ucp_Repair","rhsusf_iotv_ucp_Rifleman","rhsusf_iotv_ucp_SAW","rhsusf_iotv_ucp_Squadleader","rhsusf_iotv_ucp_Teamleader","rhsusf_spc","rhsusf_spc_rifleman","rhsusf_spc_iar","rhsusf_spc_corpsman","rhsusf_spc_crewman","rhsusf_spc_light","rhsusf_spc_marksman","rhsusf_spc_mg","rhsusf_spc_squadleader","rhsusf_spc_teamleader","rhsusf_spc_patchless","rhsusf_spc_patchless_radio","rhsusf_spcs_ocp","rhsusf_spcs_ocp_rifleman","rhsusf_spcs_ucp","rhsusf_spcs_ucp_rifleman","rhsusf_mbav","rhsusf_mbav_light","rhsusf_mbav_rifleman","rhsusf_mbav_mg","rhsusf_mbav_grenadier","rhsusf_mbav_medic"]

rand_backpacks = ["rhsusf_assault_eagleaiii_ocp","rhssaf_kitbag_md2camo","rhssaf_kitbag_digital","rhssaf_kitbag_smb","rhssaf_alice_md2camo","rhssaf_alice_smb","RHS_NSV_Gun_Bag","RHS_NSV_Tripod_Bag","RHS_DShkM_Gun_Bag","RHS_DShkM_TripodHigh_Bag","RHS_DShkM_TripodLow_Bag","RHS_Kord_Gun_Bag","RHS_Kord_Tripod_Bag","RHS_Metis_Gun_Bag","RHS_Metis_Tripod_Bag","RHS_Kornet_Gun_Bag","RHS_Kornet_Tripod_Bag","RHS_AGS30_Gun_Bag","RHS_AGS30_Tripod_Bag","RHS_SPG9_Gun_Bag","RHS_SPG9_Tripod_Bag","RHS_Podnos_Gun_Bag","RHS_Podnos_Bipod_Bag","rhs_assault_umbts","rhs_assault_umbts_engineer_empty","rhs_rpg_empty","rhs_sidor","rhs_medic_bag","rhs_d6_Parachute_backpack","rhsgref_hidf_alicepack","rhsgref_wdl_alicepack","rhsgref_ttsko_alicepack","rhsusf_assault_eagleaiii_ucp","rhsusf_assault_eagleaiii_coy","rhsusf_falconii","rhsusf_falconii_coy","rhsusf_falconii_mc","RHS_M2_Gun_Bag","RHS_M2_Tripod_Bag","RHS_M2_MiniTripod_Bag","RHS_Mk19_Gun_Bag","RHS_Mk19_Tripod_Bag","rhs_Tow_Gun_Bag","rhs_TOW_Tripod_Bag","rhs_M252_Gun_Bag","rhs_M252_Bipod_Bag"];

//rand_backpacks = "(_x call smm_fnc_macrosIsGood) and (_x call smm_fnc_macrosIsBackpack) && (count (configName _x) > 3) && (toLower ((configName _x) select [0,3])) == 'rhs'" configClasses (configFile >> "CfgVehicles") apply {configName _x};
private _rhsitems = ("(_x call smm_fnc_macrosIsGood) and (_x call smm_fnc_macrosIsItem) and (_x call smm_is_not_thermal) && (count (configName _x) > 3) && ((toLower(configName _x)) select [0,3]) == 'rhs'" configClasses (configFile >> "CfgWeapons")) apply {configName _x};

private _rhsitems = ["rhssaf_helmet_m59_85_nocamo","rhssaf_helmet_m59_85_oakleaf","rhssaf_helmet_m97_olive_nocamo","rhssaf_helmet_m97_olive_nocamo_black_ess","rhssaf_helmet_m97_olive_nocamo_black_ess_bare","rhssaf_helmet_m97_black_nocamo","rhssaf_helmet_m97_black_nocamo_black_ess","rhssaf_helmet_m97_black_nocamo_black_ess_bare","rhssaf_helmet_m97_woodland","rhssaf_helmet_m97_digital","rhssaf_helmet_m97_md2camo","rhssaf_helmet_m97_oakleaf","rhssaf_helmet_m97_nostrap_blue","rhssaf_helmet_m97_nostrap_blue_tan_ess","rhssaf_helmet_m97_nostrap_blue_tan_ess_bare","rhssaf_helmet_m97_woodland_black_ess","rhssaf_helmet_m97_digital_black_ess","rhssaf_helmet_m97_md2camo_black_ess","rhssaf_helmet_m97_oakleaf_black_ess","rhssaf_helmet_m97_woodland_black_ess_bare","rhssaf_helmet_m97_digital_black_ess_bare","rhssaf_helmet_m97_md2camo_black_ess_bare","rhssaf_helmet_m97_oakleaf_black_ess_bare","rhssaf_beret_green","rhssaf_beret_red","rhssaf_beret_para","rhssaf_beret_black","rhssaf_beret_blue_un","rhs_booniehat2_marpatd","rhssaf_booniehat_digital","rhssaf_booniehat_md2camo","rhssaf_booniehat_woodland","rhssaf_bandana_digital","rhssaf_bandana_digital_desert","rhssaf_bandana_oakleaf","rhssaf_bandana_smb","rhssaf_bandana_md2camo","rhssaf_uniform_m10_digital","rhssaf_uniform_m10_digital_summer","rhssaf_uniform_m10_digital_desert","rhssaf_uniform_m10_digital_tan_boots","rhssaf_uniform_m93_oakleaf","rhssaf_uniform_m93_oakleaf_summer","rhssaf_uniform_heli_pilot","rhssaf_uniform_mig29_pilot","rhssaf_uniform_gendarmes_acu","rhssaf_vest_md98_woodland","rhssaf_vest_md98_md2camo","rhssaf_vest_md98_digital","rhssaf_vest_md98_rifleman","rhssaf_vest_otv_md2camo","rhssaf_vest_md99_md2camo_rifleman","rhssaf_vest_md99_md2camo_rifleman_radio","rhssaf_vest_md99_digital_rifleman","rhssaf_vest_md99_digital_rifleman_radio","rhssaf_vest_md99_woodland_rifleman","rhssaf_vest_md99_woodland_rifleman_radio","rhssaf_vest_md99_md2camo","rhssaf_vest_md99_md2camo_radio","rhssaf_vest_md99_digital","rhssaf_vest_md99_digital_radio","rhssaf_vest_md99_woodland","rhssaf_vest_md99_woodland_radio","rhssaf_vest_md12_digital","rhssaf_vest_md12_m70_rifleman","rhssaf_vest_md12_digital_desert","rhs_bipod","rhs_acc_harris_swivel","rhs_muzzleFlash_dtk","rhs_muzzleFlash_dtk1","rhs_muzzleFlash_dtk2","rhs_muzzleFlash_dtk3","rhs_muzzleFlash_ak5","rhs_muzzleFlash_uuk","rhs_muzzleflash_pgs64","rhs_muzzleflash_dtkakm","rhs_acc_tgpa","rhs_acc_pbs1","rhs_acc_tgpv","rhs_acc_tgpv2","rhs_acc_dtk4short","rhs_acc_dtk4long","rhs_acc_dtk4screws","rhs_acc_pbs4","rhs_acc_6p9_suppressor","rhs_acc_dtk3","rhs_acc_dtk","rhs_acc_dtkakm","rhs_acc_dtk1983","rhs_acc_dtk1","rhs_acc_dtk1l","rhs_acc_dtk1p","rhs_acc_dtk2","rhs_acc_uuk","rhs_acc_ak5","rhs_acc_pgs64","rhs_acc_pgs64_74u","rhs_acc_pgs64_74un","rhs_acc_1p29","rhs_acc_1p78","rhs_acc_pkas","rhs_acc_1p63","rhs_acc_ekp1","rhs_acc_ekp8_02","rhs_acc_ekp8_18","rhs_acc_1p87","rhs_acc_pso1m2","rhs_acc_pso1m21","rhs_acc_nita","rhs_acc_pgo7v","rhs_acc_pgo7v2","rhs_acc_pgo7v3","rhs_acc_1pn93_1","rhs_acc_1pn93_2","rhs_acc_dh520x56","rhs_acc_2dpZenit","rhs_acc_2dpZenit_ris","rhs_acc_perst1ik","rhs_acc_perst1ik_ris","rhs_acc_perst3","rhs_acc_perst3_top","rhs_acc_perst3_2dp_h","rhs_acc_perst3_2dp_light_h","rhs_acc_rakursPM","rhs_acc_grip_rk2","rhs_acc_grip_rk6","rhs_acc_grip_ffg2","rhs_item_flightrecorder","rhsgref_sdn6_suppressor","rhsgref_acc_zendl","rhsusf_acc_harris_bipod","rhsusf_acc_harris_swivel","rhsusf_acc_grip1","rhsusf_acc_grip2","rhsusf_acc_grip2_tan","rhsusf_acc_grip2_wd","rhsusf_acc_grip3","rhsusf_acc_grip3_tan","rhsusf_acc_grip4","rhs_acc_at4_handler","rhsusf_acc_anpeq15A","rhsusf_acc_anpeq15","rhsusf_acc_anpeq15_bk","rhsusf_acc_anpeq15_light","rhsusf_acc_anpeq15_bk_light","rhsusf_acc_anpeq15_wmx","rhsusf_acc_anpeq15_wmx_light","rhsusf_acc_anpeq15_top","rhsusf_acc_anpeq15_bk_top","rhsusf_acc_anpeq15side","rhsusf_acc_anpeq15side_bk","rhsusf_acc_M952V","rhsusf_acc_wmx","rhsusf_acc_wmx_bk","rhsusf_acc_M2010S","rhsusf_acc_M2010S_d","rhsusf_acc_M2010S_sa","rhsusf_acc_M2010S_wd","rhsusf_acc_SR25S","rhsusf_acc_rotex5_grey","rhsusf_acc_rotex5_tan","rhsusf_acc_nt4_black","rhsusf_acc_nt4_tan","rhsusf_acc_omega9k","rhsusf_acc_rotex_mp7","rhsusf_acc_rotex_mp7_aor1","rhsusf_acc_rotex_mp7_winter","rhsusf_acc_rotex_mp7_desert","rhsusf_acc_muzzleFlash_SF3P556","rhsusf_acc_muzzleFlash_SFMB556","rhsusf_acc_muzzleFlash_ardec_m240","rhsusf_acc_SF3P556","rhsusf_acc_SFMB556","rhsusf_acc_ARDEC_M240","rhsusf_acc_compm4","rhsusf_acc_T1_high","rhsusf_acc_T1_low","rhsusf_acc_T1_low_fwd","rhsusf_acc_eotech_552","rhsusf_acc_eotech_552_d","rhsusf_acc_eotech_552_wd","rhsusf_acc_anpvs27","rhsusf_acc_LEUPOLDMK4","rhsusf_acc_ELCAN","rhsusf_acc_ELCAN_ard","rhsusf_acc_SpecterDR","rhsusf_acc_SpecterDR_D","rhsusf_acc_SpecterDR_OD","rhsusf_acc_SpecterDR_CX","rhsusf_acc_SpecterDR_A","rhsusf_acc_ACOG","rhsusf_acc_ACOG_wd","rhsusf_acc_ACOG_d","rhsusf_acc_ACOG2","rhsusf_acc_ACOG3","rhsusf_acc_ACOG_USMC","rhsusf_acc_ACOG2_USMC","rhsusf_acc_ACOG3_USMC","rhsusf_acc_ACOG_RMR","rhsusf_acc_ACOG_anpvs27","rhsusf_acc_LEUPOLDMK4_2","rhsusf_acc_LEUPOLDMK4_2_d","rhsusf_acc_premier","rhsusf_acc_premier_low","rhsusf_acc_premier_anpvs27","rhsusf_acc_M8541","rhsusf_acc_M8541_low","rhsusf_acc_M8541_low_d","rhsusf_acc_M8541_low_wd","rhsusf_acc_EOTECH","rhsusf_acc_M2A1","rhsusf_acc_eotech_xps3","rhsusf_acc_ACOG_MDO","rhsusf_acc_g33_xps3","rhsusf_acc_g33_xps3_tan","rhsusf_acc_g33_T1","rhs_weap_optic_smaw","rhs_optic_maaws","rhs_uniform_flora","rhs_uniform_df15","rhs_uniform_df15_tan","rhs_uniform_msv_emr","rhs_uniform_mvd_izlom","rhs_uniform_vdv_emr","rhs_uniform_vdv_emr_des","rhs_uniform_vdv_flora","rhs_uniform_vmf_flora","rhs_uniform_vmf_flora_subdued","rhs_uniform_rva_flora","rhs_uniform_vdv_mflora","rhs_uniform_mflora_patchless","rhs_uniform_emr_des_patchless","rhs_uniform_flora_patchless","rhs_uniform_flora_patchless_alt","rhs_uniform_emr_patchless","rhs_uniform_m88_patchless","rhs_uniform_gorka_r_y","rhs_uniform_gorka_r_g","rhs_fieldcap","rhs_fieldcap_vsr","rhs_fieldcap_digi","rhs_fieldcap_digi2","rhs_fieldcap_ml","rhs_fieldcap_khk","rhs_fieldcap_helm","rhs_fieldcap_helm_digi","rhs_fieldcap_helm_ml","rhs_beanie","rhs_beanie_green","rhs_6b26","rhs_6b26_bala","rhs_6b26_ess","rhs_6b26_ess_bala","rhs_6b26_green","rhs_6b26_bala_green","rhs_6b26_ess_green","rhs_6b26_ess_bala_green","rhs_6b27m","rhs_6b27m_digi","rhs_6b27m_ml","rhs_6b27m_ess_bala","rhs_6b27m_digi_ess_bala","rhs_6b27m_ML_ess_bala","rhs_6b27m_bala","rhs_6b27m_digi_bala","rhs_6b27m_ml_bala","rhs_6b27m_ess","rhs_6b27m_digi_ess","rhs_6b27m_ml_ess","rhs_6b27m_green","rhs_6b27m_green_ess","rhs_6b27m_green_bala","rhs_6b27m_green_ess_bala","rhs_6b28","rhs_6b28_flora","rhs_6b28_ess","rhs_6b28_flora_ess","rhs_6b28_bala","rhs_6b28_flora_bala","rhs_6b28_ess_bala","rhs_6b28_flora_ess_bala","rhs_6b28_green","rhs_6b28_green_ess","rhs_6b28_green_bala","rhs_6b28_green_ess_bala","rhs_Booniehat_digi","rhs_Booniehat_flora","rhs_ssh68","rhs_zsh7a","rhs_zsh7a_alt","rhs_zsh7a_mike","rhs_zsh7a_mike_green","rhs_zsh7a_mike_alt","rhs_zsh7a_mike_green_alt","rhs_gssh18","rhs_tsh4","rhs_tsh4_ess","rhs_tsh4_bala","rhs_tsh4_ess_bala","rhs_6b47","rhs_6b47_bala","rhs_6b47_ess","rhs_6b47_ess_bala","rhs_6b7_1m","rhs_6b7_1m_ess","rhs_6b7_1m_ess_bala","rhs_6b7_1m_bala1","rhs_6b7_1m_bala1_emr","rhs_6b7_1m_emr_ess","rhs_6b7_1m_emr_ess_bala","rhs_6b7_1m_bala1_flora","rhs_6b7_1m_bala1_olive","rhs_6b7_1m_bala2","rhs_6b7_1m_bala2_emr","rhs_6b7_1m_bala2_flora","rhs_6b7_1m_bala2_olive","rhs_6b7_1m_emr","rhs_6b7_1m_flora","rhs_6b7_1m_flora_ns3","rhs_6b7_1m_olive","rhs_altyn","rhs_altyn_bala","rhs_altyn_visordown","rhs_altyn_novisor","rhs_altyn_novisor_bala","rhs_altyn_novisor_ess","rhs_altyn_novisor_ess_bala","rhs_beret_vdv1","rhs_beret_vdv2","rhs_beret_mp1","rhs_beret_milp","rhs_beret_vdv3","rhs_beret_mp2","rhs_6b23","rhs_6b23_crew","rhs_6b23_engineer","rhs_6b23_medic","rhs_6b23_rifleman","rhs_6b23_crewofficer","rhs_6b23_sniper","rhs_6b23_6sh92","rhs_6b23_6sh92_vog","rhs_6b23_6sh92_vog_headset","rhs_6b23_6sh92_headset","rhs_6b23_6sh92_headset_mapcase","rhs_6b23_6sh92_radio","rhs_6sh46","rhs_vest_commander","rhs_vest_pistol_holster","rhs_6b23_digi","rhs_6b23_digi_crew","rhs_6b23_digi_engineer","rhs_6b23_digi_medic","rhs_6b23_digi_rifleman","rhs_6b23_digi_crewofficer","rhs_6b23_digi_sniper","rhs_6b23_digi_6sh92","rhs_6b23_digi_6sh92_vog","rhs_6b23_digi_6sh92_vog_headset","rhs_6b23_digi_6sh92_headset","rhs_6b23_digi_6sh92_headset_mapcase","rhs_6b23_digi_6sh92_radio","rhs_6b23_digi_6sh92_Spetsnaz","rhs_6b23_digi_6sh92_Vog_Radio_Spetsnaz","rhs_6b23_digi_6sh92_headset_spetsnaz","rhs_6b23_digi_6sh92_spetsnaz2","rhs_6b23_digi_6sh92_Vog_Spetsnaz","rhs_6b23_ML","rhs_6b23_ML_crew","rhs_6b23_ML_engineer","rhs_6b23_ML_medic","rhs_6b23_ML_rifleman","rhs_6b23_ML_crewofficer","rhs_6b23_ML_sniper","rhs_6b23_ML_6sh92","rhs_6b23_ML_6sh92_vog","rhs_6b23_ML_6sh92_vog_headset","rhs_6b23_ML_6sh92_headset","rhs_6b23_ML_6sh92_headset_mapcase","rhs_6b23_ML_6sh92_radio","rhs_vydra_3m","rhs_6b23_vydra_3m","rhs_6b23_digi_vydra_3m","rhs_6b23_ML_vydra_3m","rhs_6b23_6sh116","rhs_6b23_6sh116_flora","rhs_6b23_6sh116_od","rhs_6b23_6sh116_vog","rhs_6b23_6sh116_vog_flora","rhs_6b23_6sh116_vog_od","rhs_6b13","rhs_6b13_crewofficer","rhs_6b13_6sh92","rhs_6b13_6sh92_vog","rhs_6b13_6sh92_headset_mapcase","rhs_6b13_6sh92_radio","rhs_6b13_EMR","rhs_6b13_EMR_6sh92","rhs_6b13_EMR_6sh92_vog","rhs_6b13_EMR_6sh92_headset_mapcase","rhs_6b13_EMR_6sh92_radio","rhs_6b13_Flora","rhs_6b13_Flora_crewofficer","rhs_6b13_Flora_6sh92","rhs_6b13_Flora_6sh92_vog","rhs_6b13_Flora_6sh92_headset_mapcase","rhs_6b13_Flora_6sh92_radio","rhs_6b43","rhs_6sh92","rhs_6sh92_vog","rhs_6sh92_vog_headset","rhs_6sh92_headset","rhs_6sh92_radio","rhs_6sh92_digi","rhs_6sh92_digi_vog","rhs_6sh92_digi_vog_headset","rhs_6sh92_digi_headset","rhs_6sh92_digi_radio","rhs_6sh92_vsr","rhs_6sh92_vsr_vog","rhs_6sh92_vsr_vog_headset","rhs_6sh92_vsr_headset","rhs_6sh92_vsr_radio","rhsgref_uniform_ttsko_forest","rhsgref_uniform_ttsko_mountain","rhsgref_uniform_ttsko_urban","rhsgref_uniform_vsr","rhsgref_uniform_para_ttsko_oxblood","rhsgref_uniform_para_ttsko_mountain","rhsgref_uniform_para_ttsko_urban","rhsgref_uniform_specter","rhsgref_uniform_reed","rhsgref_uniform_alpenflage","rhsgref_uniform_flecktarn","rhsgref_uniform_flecktarn_full","rhsgref_uniform_tigerstripe","rhsgref_uniform_woodland","rhsgref_uniform_woodland_olive","rhsgref_uniform_ERDL","rhsgref_uniform_og107","rhsgref_uniform_og107_erdl","rhsgref_uniform_altis_lizard","rhsgref_uniform_olive","rhsgref_uniform_altis_lizard_olive","rhsgref_uniform_dpm","rhsgref_uniform_dpm_olive","rhsgref_uniform_3color_desert","rhsgref_un_beret","rhsgref_Booniehat_alpen","rhsgref_bcap_specter","rhsgref_patrolcap_specter","rhsgref_fieldcap_ttsko_forest","rhsgref_fieldcap_ttsko_mountain","rhsgref_fieldcap_ttsko_urban","rhsgref_fieldcap_ttsko_digi","rhsgref_ssh68_ttsko_mountain","rhsgref_ssh68_ttsko_forest","rhsgref_ssh68_ttsko_dark","rhsgref_ssh68_ttsko_digi","rhsgref_ssh68_emr","rhsgref_ssh68_un","rhsgref_ssh68_vsr","rhsgref_M56","rhsgref_6b27m_ttsko_forest","rhsgref_6b27m_ttsko_mountain","rhsgref_6b27m_ttsko_urban","rhsgref_6b27m_ttsko_digi","rhsgref_helmet_M1_bare","rhsgref_helmet_M1_bare_alt01","rhsgref_helmet_M1_painted","rhsgref_helmet_M1_painted_alt01","rhsgref_helmet_pasgt_erdl","rhsgref_helmet_pasgt_erdl_rhino","rhsgref_helmet_pasgt_woodland","rhsgref_helmet_pasgt_woodland_rhino","rhsgref_helmet_pasgt_flecktarn","rhsgref_helmet_pasgt_un","rhsgref_helmet_pasgt_press","rhsgref_helmet_pasgt_3color_desert","rhsgref_helmet_pasgt_3color_desert_rhino","rhsgref_helmet_pasgt_altis_lizard","rhsgref_helmet_pasgt_olive","rhsgref_6b23_khaki","rhsgref_6b23_khaki_rifleman","rhsgref_6b23_khaki_sniper","rhsgref_6b23_khaki_officer","rhsgref_6b23_khaki_nco","rhsgref_6b23_khaki_medic","rhsgref_6b23_ttsko_forest","rhsgref_6b23_ttsko_forest_rifleman","rhsgref_6b23_ttsko_mountain","rhsgref_6b23_ttsko_mountain_rifleman","rhsgref_6b23_ttsko_mountain_sniper","rhsgref_6b23_ttsko_mountain_officer","rhsgref_6b23_ttsko_mountain_nco","rhsgref_6b23_ttsko_mountain_medic","rhsgref_6b23_ttsko_digi","rhsgref_6b23_ttsko_digi_rifleman","rhsgref_6b23_ttsko_digi_sniper","rhsgref_6b23_ttsko_digi_officer","rhsgref_6b23_ttsko_digi_nco","rhsgref_6b23_ttsko_digi_medic","rhs_6b5","rhs_6b5_officer","rhs_6b5_medic","rhs_6b5_sniper","rhs_6b5_khaki","rhs_6b5_officer_khaki","rhs_6b5_medic_khaki","rhs_6b5_sniper_khaki","rhs_6b5_vsr","rhs_6b5_officer_vsr","rhs_6b5_medic_vsr","rhs_6b5_sniper_vsr","rhs_6b5_ttsko","rhs_6b5_officer_ttsko","rhs_6b5_medic_ttsko","rhs_6b5_sniper_ttsko","rhsgref_otv_khaki","rhsgref_otv_digi","rhsgref_TacVest_ERDL","rhsgref_alice_webbing","rhs_uniform_g3_mc","rhs_uniform_g3_m81","rhs_uniform_g3_tan","rhs_uniform_g3_rgr","rhs_uniform_g3_blk","rhs_uniform_cu_ocp","rhs_uniform_cu_ucp","rhs_uniform_cu_ocp_1stcav","rhs_uniform_cu_ucp_1stcav","rhs_uniform_cu_ocp_82nd","rhs_uniform_cu_ucp_82nd","rhs_uniform_cu_ocp_101st","rhs_uniform_cu_ucp_101st","rhs_uniform_cu_ocp_10th","rhs_uniform_cu_ucp_10th","rhs_uniform_FROG01_d","rhs_uniform_FROG01_wd","rhs_uniform_acu_ucp","rhsusf_patrolcap_ocp","rhsusf_patrolcap_ucp","rhs_Booniehat_ocp","rhs_Booniehat_ucp","rhs_Booniehat_m81","rhs_booniehat2_marpatwd","rhs_8point_marpatd","rhs_8point_marpatwd","rhsusf_ach_helmet_ocp","rhsusf_ach_helmet_ocp_norotos","rhsusf_ach_helmet_ucp","rhsusf_ach_helmet_ucp_norotos","rhsusf_ach_helmet_M81","rhsusf_ach_helmet_camo_ocp","rhsusf_ach_helmet_headset_ocp","rhsusf_ach_helmet_headset_ucp","rhsusf_ach_helmet_ESS_ocp","rhsusf_ach_helmet_ESS_ucp","rhsusf_ach_helmet_headset_ess_ocp","rhsusf_ach_helmet_headset_ess_ucp","rhsusf_ach_bare","rhsusf_ach_bare_ess","rhsusf_ach_bare_headset","rhsusf_ach_bare_headset_ess","rhsusf_ach_bare_tan","rhsusf_ach_bare_tan_ess","rhsusf_ach_bare_tan_headset","rhsusf_ach_bare_tan_headset_ess","rhsusf_ach_bare_wood","rhsusf_ach_bare_wood_ess","rhsusf_ach_bare_wood_headset","rhsusf_ach_bare_wood_headset_ess","rhsusf_ach_bare_des","rhsusf_ach_bare_des_ess","rhsusf_ach_bare_des_headset","rhsusf_ach_bare_des_headset_ess","rhsusf_ach_bare_semi","rhsusf_ach_bare_semi_ess","rhsusf_ach_bare_semi_headset","rhsusf_ach_bare_semi_headset_ess","rhsusf_opscore_fg","rhsusf_opscore_fg_pelt","rhsusf_opscore_fg_pelt_nsw","rhsusf_opscore_fg_pelt_cam","rhsusf_opscore_ut","rhsusf_opscore_ut_pelt","rhsusf_opscore_ut_pelt_cam","rhsusf_opscore_ut_pelt_nsw","rhsusf_opscore_ut_pelt_nsw_cam","rhsusf_opscore_bk","rhsusf_opscore_bk_pelt","rhsusf_opscore_mc","rhsusf_opscore_mc_pelt","rhsusf_opscore_mc_pelt_nsw","rhsusf_opscore_aor1","rhsusf_opscore_aor1_pelt","rhsusf_opscore_aor1_pelt_nsw","rhsusf_opscore_aor2","rhsusf_opscore_aor2_pelt","rhsusf_opscore_aor2_pelt_nsw","rhsusf_opscore_paint","rhsusf_opscore_paint_pelt","rhsusf_opscore_paint_pelt_nsw","rhsusf_opscore_paint_pelt_nsw_cam","rhsusf_opscore_mc_cover","rhsusf_opscore_mc_cover_pelt","rhsusf_opscore_mc_cover_pelt_nsw","rhsusf_opscore_mc_cover_pelt_cam","rhsusf_opscore_rg_cover","rhsusf_opscore_rg_cover_pelt","rhsusf_opscore_coy_cover","rhsusf_opscore_coy_cover_pelt","rhsusf_opscore_mar_ut","rhsusf_opscore_mar_ut_pelt","rhsusf_opscore_mar_fg","rhsusf_opscore_mar_fg_pelt","rhsusf_cvc_helmet","rhsusf_cvc_alt_helmet","rhsusf_cvc_green_helmet","rhsusf_cvc_green_alt_helmet","rhsusf_cvc_ess","rhsusf_cvc_green_ess","rhsusf_hgu56p","rhsusf_hgu56p_visor","rhsusf_hgu56p_mask","rhsusf_hgu56p_visor_mask","rhsusf_hgu56p_visor_mask_skull","rhsusf_hgu56p_mask_skull","rhsusf_hgu56p_visor_mask_mo","rhsusf_hgu56p_mask_mo","rhsusf_hgu56p_mask_smiley","rhsusf_hgu56p_visor_mask_smiley","rhsusf_hgu56p_black","rhsusf_hgu56p_visor_black","rhsusf_hgu56p_mask_black","rhsusf_hgu56p_visor_mask_black","rhsusf_hgu56p_visor_mask_black_skull","rhsusf_hgu56p_mask_black_skull","rhsusf_hgu56p_visor_mask_Empire_black","rhsusf_hgu56p_green","rhsusf_hgu56p_visor_green","rhsusf_hgu56p_mask_green","rhsusf_hgu56p_visor_mask_green","rhsusf_hgu56p_mask_green_mo","rhsusf_hgu56p_visor_mask_green_mo","rhsusf_hgu56p_pink","rhsusf_hgu56p_visor_pink","rhsusf_hgu56p_mask_pink","rhsusf_hgu56p_visor_mask_pink","rhsusf_hgu56p_usa","rhsusf_hgu56p_visor_usa","rhsusf_hgu56p_saf","rhsusf_hgu56p_visor_saf","rhsusf_hgu56p_mask_saf","rhsusf_hgu56p_visor_mask_saf","rhsusf_mich_helmet_marpatwd","rhsusf_mich_helmet_marpatwd_headset","rhsusf_mich_helmet_marpatd","rhsusf_mich_helmet_marpatd_headset","rhsusf_mich_helmet_marpatwd_alt","rhsusf_mich_helmet_marpatwd_alt_headset","rhsusf_mich_helmet_marpatd_alt","rhsusf_mich_helmet_marpatd_alt_headset","rhsusf_mich_helmet_marpatwd_norotos","rhsusf_mich_helmet_marpatwd_norotos_headset","rhsusf_mich_helmet_marpatd_norotos","rhsusf_mich_helmet_marpatd_norotos_headset","rhsusf_mich_helmet_marpatwd_norotos_arc","rhsusf_mich_helmet_marpatwd_norotos_arc_headset","rhsusf_mich_helmet_marpatd_norotos_arc","rhsusf_mich_helmet_marpatd_norotos_arc_headset","rhsusf_mich_bare","rhsusf_mich_bare_headset","rhsusf_mich_bare_alt","rhsusf_mich_bare_norotos","rhsusf_mich_bare_norotos_headset","rhsusf_mich_bare_norotos_alt","rhsusf_mich_bare_norotos_alt_headset","rhsusf_mich_bare_norotos_arc","rhsusf_mich_bare_norotos_arc_headset","rhsusf_mich_bare_norotos_arc_alt","rhsusf_mich_bare_norotos_arc_alt_headset","rhsusf_mich_bare_tan","rhsusf_mich_bare_tan_headset","rhsusf_mich_bare_alt_tan","rhsusf_mich_bare_norotos_tan","rhsusf_mich_bare_norotos_tan_headset","rhsusf_mich_bare_norotos_alt_tan","rhsusf_mich_bare_norotos_alt_tan_headset","rhsusf_mich_bare_norotos_arc_tan","rhsusf_mich_bare_norotos_arc_alt_tan","rhsusf_mich_bare_norotos_arc_alt_tan_headset","rhsusf_mich_bare_semi","rhsusf_mich_bare_semi_headset","rhsusf_mich_bare_alt_semi","rhsusf_mich_bare_norotos_semi","rhsusf_mich_bare_norotos_semi_headset","rhsusf_mich_bare_norotos_alt_semi","rhsusf_mich_bare_norotos_alt_semi_headset","rhsusf_mich_bare_norotos_arc_semi","rhsusf_mich_bare_norotos_arc_semi_headset","rhsusf_mich_bare_norotos_arc_alt_semi","rhsusf_mich_bare_norotos_arc_alt_semi_headset","rhsusf_lwh_helmet_marpatd","rhsusf_lwh_helmet_marpatd_ess","rhsusf_lwh_helmet_marpatd_headset","rhsusf_lwh_helmet_marpatwd","rhsusf_lwh_helmet_marpatwd_ess","rhsusf_lwh_helmet_marpatwd_blk_ess","rhsusf_lwh_helmet_marpatwd_headset","rhsusf_lwh_helmet_marpatwd_headset_blk","rhsusf_lwh_helmet_M1942","rhsusf_Bowman","rhsusf_bowman_cap","RHS_jetpilot_usaf","rhsusf_protech_helmet","rhsusf_protech_helmet_ess","rhsusf_protech_helmet_rhino","rhsusf_protech_helmet_rhino_ess","rhsusf_iotv_ocp","rhsusf_iotv_ocp_Grenadier","rhsusf_iotv_ocp_Medic","rhsusf_iotv_ocp_Repair","rhsusf_iotv_ocp_Rifleman","rhsusf_iotv_ocp_SAW","rhsusf_iotv_ocp_Squadleader","rhsusf_iotv_ocp_Teamleader","rhsusf_iotv_ucp","rhsusf_iotv_ucp_Grenadier","rhsusf_iotv_ucp_Medic","rhsusf_iotv_ucp_Repair","rhsusf_iotv_ucp_Rifleman","rhsusf_iotv_ucp_SAW","rhsusf_iotv_ucp_Squadleader","rhsusf_iotv_ucp_Teamleader","rhsusf_spc","rhsusf_spc_rifleman","rhsusf_spc_iar","rhsusf_spc_corpsman","rhsusf_spc_crewman","rhsusf_spc_light","rhsusf_spc_marksman","rhsusf_spc_mg","rhsusf_spc_squadleader","rhsusf_spc_teamleader","rhsusf_spc_patchless","rhsusf_spc_patchless_radio","rhsusf_spcs_ocp","rhsusf_spcs_ocp_rifleman","rhsusf_spcs_ucp","rhsusf_spcs_ucp_rifleman","rhsusf_mbav","rhsusf_mbav_light","rhsusf_mbav_rifleman","rhsusf_mbav_mg","rhsusf_mbav_grenadier","rhsusf_mbav_medic"]