class filterZonesFromSide{};
class getNeighboursFromMultiple{};
class cleanupTargets{};
class getUnits{};
class getZoneCandidates{};
class getOverlappingFromCandidates{};
class advancedZoneGenerator{};
class getIndependentSetFromCandidates{};
class triangulateCandidates{};